os: osx
osx_image: xcode8.3
addons:
  homebrew:
    casks:
      -osxfuse
script:
  - "mkdir -p /tmp/brfs"
  - "./brfs /tmp/brfs &"
  - sleep 5
  - cat /tmp/brfs/digest/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-0
